

site_name: Software Pico - 1MTR53
site_author: Equipo 1MTR53


repo_url: https://github.com/PUCP-Robotica-IA/Software_Pico 
repo_name: Ver en GitHub
edit_uri: edit/main/docs/ 


theme:
  name: readthedocs
  
  locale: es

  navigation_depth: 4
  collapse_navigation: false 
  sticky_navigation: true
  
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - markdown

  features:
    - content.code.copy
    - content.code.select

nav:
  - 'Introducción': 'index.md'
  - 'Guía de instalación':
    - 'Guía 1: Instalación del firmware del Micropython' : 'guides/micropython_guide.md'
    - 'Guía 2: Tu primer programa con Thonny' : 'guides/thony_guide.md'
    - 'Guía 3: Carga de archivos base': 'guides/base_guide.md'
  - 'Configuración': 
    - 'Configuración de pines': 'configure/configure.md'
    - 'Configuración y calibración de motores': 'configure/motor_config_guide.md'
  - 'Robot': 
    - 'Robot': 'robot/robot.md'
  # - 'Spring documentos':
  #   # - 'Spring 2024': 'spring2024/spring2024.md'
  # - 'Sensores':
  #   - 'sensor': 'sensors/sensor.md'
  #   - 'ultrasonido': 'sensors/ultrasonico.md'
  # - 'Pruebas':
  #   - 'prueba1': 'test/test.md'
  # - 'Códigos útiles':
  #   - 'utilidad': 'utils/util.md'

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  


